name: google_ml_kit_example
description: Demonstrates how to use the google_ml_kit plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  camera: ^0.10.0+4
  path: ^1.8.2
  path_provider: ^2.0.11

  #  google_ml_kit:
  #    path: ../
  google_mlkit_commons: any
  #    path: ../../google_mlkit_commons
  google_mlkit_barcode_scanning: any
  google_mlkit_digital_ink_recognition: any
  google_mlkit_face_detection: any
  google_mlkit_image_labeling: any
  google_mlkit_object_detection: any
  google_mlkit_pose_detection: any
  google_mlkit_selfie_segmentation: any
  google_mlkit_text_recognition: any

  google_mlkit_entity_extraction: any
  google_mlkit_language_id: any
  google_mlkit_translation: any
  google_mlkit_smart_reply: any

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ml/
